language: node_js
node_js:
  - "node"
script: "npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
notifications:
  branches:
    only:
      - "master"
      - "Develop"
  slack: stsiinc:pAsVjY5Hb5NxQ6RPOhYmuLuv
