language: node_js
node_js:
  - "node"
before_install: "cd learning-lab-app"
script: "npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
cache:
  directories:
    - "node_modules"
